name: Build and Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      VALIDATE_ONLY:
        description: Make it true, if only build is required
        required: false
        type: boolean
        default: true

      CONFIGURATION:
        description: Configuration to build.
        required: true
        type: string

      NUGET_CONFIG_FILE:
        description: Path to the NuGet configuration file relative to the repository root.
        required: false
        type: string
        default: src/NuGet.config

      REQUIRED_GIT_REPOS_FILE:
        description: Path to the required git repositories file relative to the repository root.
        required: false
        type: string
        default: required-git-repos.json

      deployVersion:
        description: Version to deploy
        required: false
        type: string
        default: latest

      deployTarget:
        description: Deployment targets (comma-separated)
        required: false
        type: string
        default: DevTest

jobs:
  build:
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/build.yaml@master
    with:
      buildType: ${{ github.event.inputs.buildType || 'full' }}
      CONFIGURATION: ${{ github.event.inputs.CONFIGURATION }}
    # Always run build on any trigger
    # No condition needed unless you want to exclude deploy-only manual runs

  deploy:
    # Run deploy only if:
    # - It’s NOT a workflow_dispatch (e.g., push/pull_request), OR
    # - VALIDATE_ONLY is explicitly false (manual run)
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.VALIDATE_ONLY == 'false'
    needs: build
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/deploy.yaml@master
    with:
      deployVersion: ${{ github.event.inputs.deployVersion || 'latest' }}
      deployTarget: ${{ github.event.inputs.deployTarget || 'DevTest' }}
