name: Build and Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      VALIDATE_ONLY:
        description: Only build, do not deploy
        required: false
        default: true
        type: boolean
      CONFIGURATION:
        description: Build configuration
        required: true
        default: release
        type: string
      deployVersion:
        description: Version to deploy
        required: false
        default: latest
        type: string
      deployTarget:
        description: Deploy target(s)
        required: false
        default: DevTest
        type: string

jobs:
  build:
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/build.yaml@master
    with:
      buildType: ${{ github.event.inputs.buildType || 'full' }}
      CONFIGURATION: ${{ github.event.inputs.CONFIGURATION }}
      VALIDATE_ONLY: ${{ github.event.inputs.VALIDATE_ONLY }}

  deploy:
    needs: build
    if: ${{ inputs.VALIDATE_ONLY == 'false' }}
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/deploy.yaml@master
    with:
      deployVersion: ${{ github.event.inputs.deployVersion || 'latest' }}
      deployTarget: ${{ github.event.inputs.deployTarget || 'DevTest' }}
