name: Trigger Deployment Workflow
 
on:
  push:
    branches:
      - main
 
jobs:
  call-deployment:
    uses: ./.github/workflows/testManualplusAutomaticTriggerEvents.yaml
    with:
      environment: production
      version: v1.2.3
