name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      runMode:
        description: |
        What to do:
        - build: Run build only
        - deploy: Run deploy only
        - build-and-deploy: Do both
        required: true
        type: choice
        options: [build, deploy, build-and-deploy]
      
      # 🔧 Build-only inputs
      build_productName:
        description: (Build only) Product name
        type: string
        required: false
      
      buildType:
        description: (Build only) Build type (e.g. full/incremental)
        type: string
        required: false
        default: full
      
      # 🚀 Deploy-only inputs
      deploy_productName:
        description: (Deploy only) Product name
        type: string
        required: false
        
      deployVersion:
        description: (Deploy only) Version to deploy
        type: string
        required: false

jobs:
  manual-build:
    if: inputs.runMode == 'build' || inputs.runMode == 'build-and-deploy'
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/build.yaml@master
    with:
      productName: ${{ inputs.productName }}
      buildType: ${{ inputs.buildType }}
      skipTests: ${{ inputs.skipTests }}
      deployAfterBuild: ${{ inputs.runMode == 'build-and-deploy' }}
      deployVersion: ${{ inputs.deployVersion }}
      deployConfiguration: ${{ inputs.deployConfiguration }}
      deployTarget: ${{ inputs.deployTarget }}

  manual-deploy:
    if: inputs.runMode == 'deploy'
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/deploy.yaml@master
    with:
      productName: ${{ inputs.productName }}
      deployVersion: ${{ inputs.deployVersion }}
      deployConfiguration: ${{ inputs.deployConfiguration }}
      deployTarget: ${{ inputs.deployTarget }}
