name: Release Workflow

on:
  workflow_call:
    inputs:
      deployVersion:
        required: true
        type: string
      deployTarget:
        required: false
        type: string
        default: DevTest

  workflow_dispatch:
    inputs:
      deployVersion:
        description: Version to deploy
        required: true
        type: string
      deployTarget:
        description: Deploy target(s)
        required: false
        default: DevTest
        type: string

jobs:
  deploy:
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/deploy.yaml@master
    with:
      deployVersion: ${{ inputs.deployVersion }}
      deployTarget: ${{ inputs.deployTarget }}
