name: Release Workflow

on:
  workflow_call:
    inputs:
      productName:
        required: true
        type: string
      deployVersion:
        required: true
        type: string
      deployConfiguration:
        required: false
        type: string
        default: release
      deployTarget:
        required: false
        type: string
        default: DevTest

  workflow_dispatch:
    inputs:
      productName:
        description: Product to deploy
        required: true
        type: string
      deployVersion:
        description: Version to deploy
        required: true
        type: string
      deployConfiguration:
        description: Configuration to deploy
        required: false
        type: string
        default: release
      deployTarget:
        description: Target environments (comma-separated)
        required: false
        type: string
        default: DevTest

jobs:
  deploy:
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/deploy.yaml@master
    with:
      productName: ${{ inputs.productName }}
      deployVersion: ${{ inputs.deployVersion }}
      deployConfiguration: ${{ inputs.deployConfiguration }}
      deployTarget: ${{ inputs.deployTarget }}
